### ISSUE TITLE
Bug: Build errors while updating data

### ISSUE THREAD

**Issue by ZeldaZach** [dr4fters/dr4ft#1431]
https://paste.ee/p/2BdFG

```
2021-02-02 01:13:15,205-0500 [ERROR] [GLOBAL] Error while integrating the file /var/www/dr4ft.info/dr4ft/data/sets/CELD.json: TypeError: Cannot read property 'code' of undefined
    at /var/www/dr4ft.info/dr4ft/scripts/update_database.js:28:18
    at Array.forEach (<anonymous>)
    at updateDatabase (/var/www/dr4ft.info/dr4ft/scripts/update_database.js:17:11)
    at download (/var/www/dr4ft.info/dr4ft/scripts/download_allsets.js:67:5)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at runNextTicks (internal/process/task_queues.js:66:3)
    at processImmediate (internal/timers.js:429:9)

(This happens for several sets, mostly promo sets)
```

**Comment by ZeldaZach** [comment]
Looks to be related to the sets/ folder within data not clearing correctly... that's interesting. I flushed it out and rebuilt w/o issues
