### ISSUE TITLE
Problems Installing Native or Docker

### ISSUE THREAD

**Issue by Zeropeace** [dr4fters/dr4ft#1547]
Hello devs,

i love the thing you have made here and i would like to make a small offline version for use with my play group.
I have been trying for 2 days to install the app either with your native instructions or Docker ones. None seem to work.
I have been trying to set this up on Ubuntu18.04, 20.04 and CentOS 7,8 same problems. here is a quick post from the errors i keep getting.

**When i try to install with docker:**

> draft@1.0.0 postinstall /app
>  npm run download_allsets && webpack --config webpack.prod.js

> draft@1.0.0 download_allsets /app
> node scripts/download_allsets

fatal: not a git repository (or any of the parent directories): .git
Error: Command failed: git describe --tags
fatal: not a git repository (or any of the parent directories): .git

    at checkExecSyncError (child_process.js:630:11)
    at execSync (child_process.js:666:15)
    at Object.<anonymous> (/app/config/version.js:8:17)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/app/config/index.js:3:17)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18) {
  status: 128,
  signal: null,
  output: [
    null,
    <Buffer >,
    <Buffer 66 61 74 61 6c 3a 20 6e 6f 74 20 61 20 67 69 74 20 72 65 70 6f 73 69 74 6f 72 79 20 28 6f 72 20 61 6e 79 20 6f 66 20 74 68 65 20 70 61 72 65 6e 74 20 ... 19 more bytes>
  ],
  pid: 108,
  stdout: <Buffer >,
  stderr: <Buffer 66 61 74 61 6c 3a 20 6e 6f 74 20 61 20 67 69 74 20 72 65 70 6f 73 69 74 6f 72 79 20 28 6f 72 20 61 6e 79 20 6f 66 20 74 68 65 20 70 61 72 65 6e 74 20 ... 19 more bytes>
}
2021-08-01 12:04:23,125+0000 [INFO] Checking if AllSets.json is up to date
2021-08-01 12:04:23,371+0000 [ERROR] Error while fetching version to https://www.mtgjson.com/files/version.json: SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/app/scripts/download_allsets.js:25:38)
    at IncomingMessage.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
2021-08-01 12:04:23,372+0000 [ERROR] Couldn't complete AllSets.json check : undefined
Hash: c8df3962ea93d449d73f
Version: webpack 4.42.0
Time: 21510ms
Built at: 08/01/2021 12:04:46 PM
                                            Asset       Size  Chunks                         Chunk Names
                       10-c8df3962ea93d449d73f.js    107 KiB      10  [emitted] [immutable]
                                         4-hq.png   16.2 KiB          [emitted]
                                            4.png  978 bytes          [emitted]
                        7-c8df3962ea93d449d73f.js   43.7 KiB       7  [emitted] [immutable]
                        8-c8df3962ea93d449d73f.js   34.6 KiB       8  [emitted] [immutable]
                        9-c8df3962ea93d449d73f.js   14.8 KiB       9  [emitted] [immutable]
             app~c5b24172-c8df3962ea93d449d73f.js   16.7 KiB       0  [emitted] [immutable]  app~c5b24172
                                      favicon.ico   14.7 KiB          [emitted]
                                       index.html   1.49 KiB          [emitted]
                                      media/B.svg   2.62 KiB          [emitted]
                                      media/G.svg   2.85 KiB          [emitted]
                                      media/R.svg   2.59 KiB          [emitted]
                                      media/U.svg  753 bytes          [emitted]
                                      media/W.svg   3.32 KiB          [emitted]
                             media/arrow-down.png   5.89 KiB          [emitted]
                               media/arrow-up.png    5.8 KiB          [emitted]
                                   media/beep.wav  828 bytes          [emitted]
                                   media/foil.png   66.4 KiB          [emitted]
                 polyfill-c8df3962ea93d449d73f.js   1.52 KiB       1  [emitted] [immutable]  polyfill
                                        style.css   8.09 KiB          [emitted]
     vendors~app~2a42e354-c8df3962ea93d449d73f.js   70.6 KiB       2  [emitted] [immutable]  vendors~app~2a42e354
     vendors~app~77bf5e45-c8df3962ea93d449d73f.js   71.2 KiB       3  [emitted] [immutable]  vendors~app~77bf5e45
     vendors~app~7d359b94-c8df3962ea93d449d73f.js    136 KiB       4  [emitted] [immutable]  vendors~app~7d359b94
vendors~polyfill~253ae210-c8df3962ea93d449d73f.js   73.1 KiB       5  [emitted] [immutable]  vendors~polyfill~253ae210
vendors~polyfill~d939e436-c8df3962ea93d449d73f.js   74.1 KiB       6  [emitted] [immutable]  vendors~polyfill~d939e436
Entrypoint polyfill = vendors~polyfill~253ae210-c8df3962ea93d449d73f.js vendors~polyfill~d939e436-c8df3962ea93d449d73f.js polyfill-c8df3962ea93d449d73f.js
Entrypoint app [big] = vendors~app~2a42e354-c8df3962ea93d449d73f.js vendors~app~7d359b94-c8df3962ea93d449d73f.js vendors~app~77bf5e45-c8df3962ea93d449d73f.js app~c5b24172-c8df3962ea93d449d73f.js
[0] ws (ignored) 15 bytes {0} [optional] [built]
[./frontend/src/app.js] 5.7 KiB {0} [built]
[./frontend/src/cards.js] 20.1 KiB {0} [built]
[./frontend/src/config.js] 1 KiB {0} [built]
[./frontend/src/game/Game.jsx] ./frontend/src/game/Game.jsx + 7 modules 45.7 KiB {8} [built]
    | ./frontend/src/game/Game.jsx 5.23 KiB [built]
    | ./frontend/src/game/PlayersPanel.jsx 9.02 KiB [built]
    | ./frontend/src/game/StartPanel.jsx 1.64 KiB [built]
    | ./frontend/src/game/DeckSettings.jsx 4.34 KiB [built]
    | ./frontend/src/game/GameSettings.jsx 2.94 KiB [built]
    | ./frontend/src/game/Cols.jsx 7.15 KiB [built]
    | ./frontend/src/game/Grid.jsx 7.32 KiB [built]
    | ./frontend/src/game/Chat.jsx 8.01 KiB [built]
[./frontend/src/init.js] ./frontend/src/init.js + 1 modules 2.18 KiB {0} [built]
    | ./frontend/src/init.js 150 bytes [built]
    | ./frontend/src/router.js 2.02 KiB [built]
[./frontend/src/lobby/Lobby.jsx] ./frontend/src/lobby/Lobby.jsx + 10 modules 21.4 KiB {9} [built]
    | ./frontend/src/lobby/Lobby.jsx 3.7 KiB [built]
    | ./frontend/src/lobby/Header.jsx 1.17 KiB [built]
    | ./frontend/src/lobby/JoinPanel.jsx 1.24 KiB [built]
    | ./frontend/src/lobby/NewsPanel.jsx 363 bytes [built]
    | ./frontend/src/lobby/CreatePanel.jsx 1.4 KiB [built]
    | ./frontend/src/lobby/FileUpload.jsx 2.5 KiB [built]
    | ./frontend/src/lobby/Version.jsx 984 bytes [built]
    | ./frontend/src/lobby/GameTypes.jsx 1.76 KiB [built]
    | ./frontend/src/lobby/GameOptions.jsx 3.46 KiB [built]
    | ./frontend/src/lobby/Set.jsx 1.17 KiB [built]
    | ./frontend/src/lobby/CubeList.jsx 3.67 KiB [built]
[./frontend/src/utils.jsx] 3.93 KiB {8} {9} [built]
[./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 472 bytes {4} [built]
[./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {4} [built]
    + 391 hidden modules

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  app (295 KiB)
      vendors~app~2a42e354-c8df3962ea93d449d73f.js
      vendors~app~7d359b94-c8df3962ea93d449d73f.js
      vendors~app~77bf5e45-c8df3962ea93d449d73f.js
      app~c5b24172-c8df3962ea93d449d73f.js

Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
    [./node_modules/html-webpack-plugin/lib/loader.js!./frontend/index.html.tpl] 1.09 KiB {0} [built]
    [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 472 bytes {0} [built]
    [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {0} [built]
        + 1 hidden module
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/@babel/cli/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/watchpack/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/nodemon/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/mocha/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

**When i try to install Native:**

npm WARN lifecycle draft@1.0.0~postinstall: cannot run in wd draft@1.0.0  npm run download_allsets && webpack --config webpack.prod.js (wd=/home/zeroadmin/dr4ft-1.0.0)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/@babel/cli/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/watchpack/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/nodemon/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/mocha/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

audited 1320 packages in 21.555s

**the debug.log :**

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@6.14.14
3 info using node@v12.22.4
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle draft@1.0.0~prebuild: draft@1.0.0
6 info lifecycle draft@1.0.0~build: draft@1.0.0
7 verbose lifecycle draft@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle draft@1.0.0~build: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/zeroadmin/dr4ft-1.0.>9 verbose lifecycle draft@1.0.0~build: CWD: /home/zeroadmin/dr4ft-1.0.0
10 silly lifecycle draft@1.0.0~build: Args: [ '-c', 'webpack --config webpack.prod.js' ]
11 silly lifecycle draft@1.0.0~build: Returned: code: 2  signal: null
12 info lifecycle draft@1.0.0~build: Failed to exec build script
13 verbose stack Error: draft@1.0.0 build: `webpack --config webpack.prod.js`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:314:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:314:20)
13 verbose stack     at maybeClose (internal/child_process.js:1022:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
14 verbose pkgid draft@1.0.0
15 verbose cwd /home/zeroadmin/dr4ft-1.0.0
16 verbose Linux 5.4.0-80-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
18 verbose node v12.22.4
19 verbose npm  v6.14.14
20 error code ELIFECYCLE
21 error errno 2
22 error draft@1.0.0 build: `webpack --config webpack.prod.js`
22 error Exit status 2
23 error Failed at the draft@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]

**Comment by tooomm** [comment]
Maybe @ZeldaZach or @mixmix can help you.
