### ISSUE TITLE
BUG on A25 draft

### ISSUE THREAD

**Issue by Tamarindode5kg** [dr4fters/dr4ft#174]
I am trying do a Master 25 draft and the draft don't start...

Can i have how to fix it?

Thankful!

**Comment by HerveH44** [comment]
There's indeed an error with M25. The set is not loaded in the app ...


 @ZeldaZach @dev-id Why masters25 has type "reprint" in the AllSets.json and not "masters" like the others masters (vintage masters etc.) ?


Error :
`2018-08-22T06:53:32.941358+00:00 app[web.1]: [2018-08-22T06:53:32.941Z] draft using A25 / RIX / XLN game zq4xctp16dg started with 1 players and 8 seats
2018-08-22T06:53:32.950337+00:00 app[web.1]: /app/src/pool.js:40
2018-08-22T06:53:32.950341+00:00 app[web.1]:   var {basic, common, uncommon, rare, mythic, special, size} = set;
2018-08-22T06:53:32.950343+00:00 app[web.1]:        ^
2018-08-22T06:53:32.950344+00:00 app[web.1]: 
2018-08-22T06:53:32.950346+00:00 app[web.1]: TypeError: Cannot destructure property `basic` of 'undefined' or 'null'.
2018-08-22T06:53:32.950348+00:00 app[web.1]:     at toPack (/app/src/pool.js:40:64)
2018-08-22T06:53:32.950349+00:00 app[web.1]:     at module.exports (/app/src/pool.js:328:20)
2018-08-22T06:53:32.950351+00:00 app[web.1]:     at Game.start (/app/src/game.js:403:19)
2018-08-22T06:53:32.950353+00:00 app[web.1]:     at Object.onceWrapper (events.js:317:30)
2018-08-22T06:53:32.950354+00:00 app[web.1]:     at emitTwo (events.js:126:13)
2018-08-22T06:53:32.950356+00:00 app[web.1]:     at Sock.emit (events.js:214:7)
2018-08-22T06:53:32.950357+00:00 app[web.1]:     at Sock.message (/app/src/sock.js:13:8)
2018-08-22T06:53:32.950359+00:00 app[web.1]:     at emitOne (events.js:116:13)
2018-08-22T06:53:32.950361+00:00 app[web.1]:     at Socket.emit (events.js:211:7)
2018-08-22T06:53:32.950362+00:00 app[web.1]:     at Socket.onPacket (/app/node_modules/engine.io/lib/socket.js:110:14)
2018-08-22T06:53:33.084847+00:00 app[web.1]: fatal: Not a git repository (or any parent up to mount point /app)
2018-08-22T06:53:33.084851+00:00 app[web.1]: Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
2018-08-22T06:53:33.781017+00:00 app[web.1]: [2018-08-22T06:53:33.780Z] Started up noVersion`
