### ISSUE TITLE
Error on Custom Set Game Start

### ISSUE THREAD

**Issue by caelen-feller** [dr4fters/dr4ft#575]
When starting a game with a newly uploaded custom set, the following error occurs. (Custom set in question is called UCV, currently cannot share the json)

Have others been able to play with custom sets, or is this a problem localised to me? I can given time put together a reference custom set for testing, but have not yet. 

I have a proposed change which seems to fix this, will add when I tidy it.

```
2019-08-06 12:36:34,676+0100 [ERROR] Game a5pyte3mj0t  encountered an error while starting: TypeError: Cannot read property 'UCV' of undefined
    at /home/fellerc/Documents/mtg/dr4ft/src/pool.js:299:19
    at Array.map (<anonymous>)
    at toCards (/home/fellerc/Documents/mtg/dr4ft/src/pool.js:289:15)
    at toPack (/home/fellerc/Documents/mtg/dr4ft/src/pool.js:283:10)
    at Array.flatMap (<anonymous>)
    at /home/fellerc/Documents/mtg/dr4ft/src/pool.js:355:23
    at Array.map (<anonymous>)
    at Object.SealedNormal (/home/fellerc/Documents/mtg/dr4ft/src/pool.js:355:6)
    at Game.createPool (/home/fellerc/Documents/mtg/dr4ft/src/game.js:484:24)
    at Game.handleSealed (/home/fellerc/Documents/mtg/dr4ft/src/game.js:513:10)
    at Game.start (/home/fellerc/Documents/mtg/dr4ft/src/game.js:554:14)
    at Object.onceWrapper (events.js:291:20)
    at Sock.emit (events.js:203:13)
    at Sock.message (/home/fellerc/Documents/mtg/dr4ft/src/sock.js:15:8)
    at Socket.emit (events.js:203:13)
    at Socket.onPacket (/home/fellerc/Documents/mtg/dr4ft/node_modules/engine.io/lib/socket.js:110:14) GameState: 
    Game State
    ----------
    id: a5pyte3mj0t
    hostId: dr93lrm5gxg
    title: test
    seats: 8
    type: sealed
    sets: UCV,UCV,UCV
    isPrivate: true
    modernOnly: false
    totalChaos: false
    chaosPacksNumber: undefined
    packsInfos: UCV / UCV / UCV
    players: 1 (dr4fter)
    bots: 0   
```

**Comment by caelen-feller** [comment]
#576 Seems to resolve this issue
