### ISSUE TITLE
Site https://dr4ft.info/ is failing to load

### ISSUE THREAD

**Issue by jacketattack** [dr4fters/dr4ft#924]
When I navigate to https://dr4ft.info/, the page fails to load.

An inspection of the console reveals this error log.

```
/engine.io/?id=s4in6qneufl&name=dr4fter&EIO=3&transport=polling&t=N58duci:1 Failed to load resource: the server responded with a status of 503 ()
7-5d031e2fa5a2baa9d0de.js:1 Failed to load resource: the server responded with a status of 503 ()
vendors~app~7d359b94-5d031e2fa5a2baa9d0de.js:14 ChunkLoadError: Loading chunk 7 failed.
(error: https://dr4ft.info/7-5d031e2fa5a2baa9d0de.js)
    at Function.i.e (https://dr4ft.info/app~c5b24172-5d031e2fa5a2baa9d0de.js:1:924)
    at https://dr4ft.info/app~c5b24172-5d031e2fa5a2baa9d0de.js:1:17752
    at https://dr4ft.info/vendors~app~7d359b94-5d031e2fa5a2baa9d0de.js:14:104898
    at va (https://dr4ft.info/vendors~app~7d359b94-5d031e2fa5a2baa9d0de.js:14:105047)
    at cu (https://dr4ft.info/vendors~app~7d359b94-5d031e2fa5a2baa9d0de.js:14:96815)
    at au (https://dr4ft.info/vendors~app~7d359b94-5d031e2fa5a2baa9d0de.js:14:96740)
    at Za (https://dr4ft.info/vendors~app~7d359b94-5d031e2fa5a2baa9d0de.js:14:93770)
    at Ka (https://dr4ft.info/vendors~app~7d359b94-5d031e2fa5a2baa9d0de.js:14:90534)
    at Du (https://dr4ft.info/vendors~app~7d359b94-5d031e2fa5a2baa9d0de.js:14:111982)
    at https://dr4ft.info/vendors~app~7d359b94-5d031e2fa5a2baa9d0de.js:14:113225
ea @ vendors~app~7d359b94-5d031e2fa5a2baa9d0de.js:14
vendors~app~7d359b94-5d031e2fa5a2baa9d0de.js:30 Uncaught ChunkLoadError: Loading chunk 7 failed.
(error: https://dr4ft.info/7-5d031e2fa5a2baa9d0de.js)
    at Function.i.e (https://dr4ft.info/app~c5b24172-5d031e2fa5a2baa9d0de.js:1:924)
    at https://dr4ft.info/app~c5b24172-5d031e2fa5a2baa9d0de.js:1:17752
    at https://dr4ft.info/vendors~app~7d359b94-5d031e2fa5a2baa9d0de.js:14:104898
    at va (https://dr4ft.info/vendors~app~7d359b94-5d031e2fa5a2baa9d0de.js:14:105047)
    at cu (https://dr4ft.info/vendors~app~7d359b94-5d031e2fa5a2baa9d0de.js:14:96815)
    at au (https://dr4ft.info/vendors~app~7d359b94-5d031e2fa5a2baa9d0de.js:14:96740)
    at Za (https://dr4ft.info/vendors~app~7d359b94-5d031e2fa5a2baa9d0de.js:14:93770)
    at Ka (https://dr4ft.info/vendors~app~7d359b94-5d031e2fa5a2baa9d0de.js:14:90534)
    at Du (https://dr4ft.info/vendors~app~7d359b94-5d031e2fa5a2baa9d0de.js:14:111982)
    at https://dr4ft.info/vendors~app~7d359b94-5d031e2fa5a2baa9d0de.js:14:113225
10-5d031e2fa5a2baa9d0de.js:1 Failed to load resource: the server responded with a status of 503 ()
9-5d031e2fa5a2baa9d0de.js:1 Failed to load resource: the server responded with a status of 503 ()
/favicon.ico:1 Failed to load resource: the server responded with a status of 503 ()
```

**Comment by jacketattack** [comment]
now resolved.. site i loading
